name: Issue Forms Version Dropdown
description: |
  Populates options for a version dropdown issue forms element
  Extends ShaMan123/gha-form-dropdown-options
author: ShaMan123
branding:
  icon: hash
  color: black

inputs:
  github_token:
    description: Github token
    default: ${{ github.token }}
  template:
    description: |
      The location of the template file used to build the form, useful for ease of maintenance
      see https://github.com/ShaMan123/gha-form-dropdown-options
    type: string
  form:
    description: |
      The location of the yaml form file
      see https://github.com/ShaMan123/gha-form-dropdown-options
    default: .github/ISSUE_TEMPLATE/bug_report.yml
    type: string
  dropdown:
    description: |
      The id of the dropdown in the yaml form to populate tags into
      see https://github.com/ShaMan123/gha-form-dropdown-options
    default: version
    type: string
  package:
    description: The name of the published package
    default: ${{ github.event.repository.name }}
    type: string
  registry:
    description: The name of the registry the package is published at
    default: 'npm'
    type: string
    options:
      - npm
      - github
  order:
    description: Display order of populated tags (`asc | desc`)
    default: 'desc'
    type: choice
    options:
      - desc
      - asc
  limit_to:
    description: Limit populated tags
    type: number
  semver:
    description: A semver range query used to filter satisfying tags, see `semver#satisfies`
    type: string
  tags:
    description: |
      A stringified array of tags overriding fetching `package` tags from `registry`
      Overrides `order`, `limit_to` and dismisses outputs as well'

      Consider using https://github.com/ShaMan123/gha-form-dropdown-options directly
    type: string
  commit_message:
    description: see https://github.com/ShaMan123/gha-form-dropdown-options
    default: 'chore(): update bug report version'
    type: string
  dry_run:
    description: |
      When set to `true` will not commit the modified yaml form
      see https://github.com/ShaMan123/gha-form-dropdown-options
    default: false
    type: choice
    options:
      - true
      - false
      - no-write
      - no-commit

outputs:
  # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-declaring-outputs-for-composite-actions
  tags:
    description: A stringified array of the resulting tags
    value: ${{ steps.main.outputs.tags }}
  latest:
    description: Latest tag of `package` in `registry`
    value: ${{ steps.main.outputs.latest }}
  pushed:
    description: |
      see https://github.com/ShaMan123/gha-form-dropdown-options
    value: ${{ steps.write.outputs.pushed }}

runs:
  using: composite
  steps:
    - name: Fetch tags from ${{ inputs.registry }}:${{ inputs.package }}
      id: main
      if: ${{ !inputs.tags }}
      run: |
        node ${{ github.action_path }}/dist/main.cjs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_ORDER: ${{ inputs.order }}
        INPUT_LIMIT_TO: ${{ inputs.limit_to }}
        INPUT_SEMVER: ${{ inputs.semver }}
    - name: Set dropdown options
      id: write
      uses: ShaMan123/gha-form-dropdown-options@v1.0.1
      with:
        template: ${{ inputs.template }}
        form: ${{ inputs.form }}
        dropdown: ${{ inputs.dropdown }}
        options: ${{ inputs.tags || steps.main.outputs.tags }}
        commit_message: ${{ inputs.commit_message }}
        dry_run: ${{ inputs.dry_run }}
