name: Populate Yaml Dropdown Version
description: Populates the package version dropdown of a yaml form
author: ShaMan123
branding:
  icon: hash
  color: black
inputs:
  # github-token:
  #   description: Github token
  #   default: ${{ github.token }}
  yaml-form:
    description: 'The location of the yaml form file'
    default: '.github/ISSUE_TEMPLATE/bug_report.yml'
    type: string
  dropdown-id:
    description: 'The id of the dropdown in the yaml form to populate tags into'
    default: 'version'
    type: string
  package:
    description: 'The name of the published package'
    default: '${{ github.context.payload.repository.name }}'
    type: string
  registry:
    description: 'The name of the published package'
    default: 'npm'
    type: choice
      options:
      - npm
  order:
    description: 'Display order of populated tags (`asc | desc`)'
    default: 'desc'
    type: choice
      options:
      - desc
      - asc
  limit-to:
    description: 'limit populated tags'
    type: number
  tags:
    description: 'Provide an array of tags instead of fetching from the `registry`, overrides `package`, `registry`, `order`, `limit-to`''
  commit-message:
    default: 'chore(): update bug report version'
    type: string
outputs:
  tags:
    description: an array of the resulting tags
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
    - run: node dist/main.cjs
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ inputs.commit-message }}
