name: Issue Forms Version Dropdown
description: |
  Populates options for a version dropdown issue forms element
  Extends https://github.com/ShaMan123/gha-form-dropdown-options
author: ShaMan123
branding:
  icon: hash
  color: black

inputs:
  github_token:
    description: Github token
    default: ${{ github.token }}
  github_user:
    description: Github user
    default: github-actions[bot]
  github_email:
    description: Github email
    default: github-actions[bot]@users.noreply.github.com

  package:
    description: |
      The name of the published package
      By default infers:
      - npm package from `package.json`
      - github repo from context
    type: string

  registry:
    description: The name of the registry the package is published at
    default: npm
    type: string
    options:
      - npm
      - github

  order:
    description: Display order of populated tags
    default: desc
    type: choice
    options:
      - desc
      - asc

  limit_to:
    description: Limit populated tags
    type: number

  semver:
    description: |
      A semver range query used to filter satisfying tags
      see [semver satisfies](https://github.com/npm/node-semver#ranges-1)
    type: string

  tags:
    description: |
      A stringified array of tags overriding fetching `package` tags from `registry`
      Overrides `order`, `limit_to` and dismisses outputs as well

      Consider using https://github.com/ShaMan123/gha-form-dropdown-options directly
    type: string

  # inherited from https://github.com/ShaMan123/gha-form-dropdown-options

  template:
    description: |
      The location of the template file used to build the form, useful for ease of maintenance
    type: string

  form:
    description: |
      The location of the yaml form file
    default: .github/ISSUE_TEMPLATE/bug_report.yml
    type: string

  dropdown:
    description: |
      The id of the dropdown in the yaml form to populate tags into prefixed with $
    default: _version
    type: string

  label:
    description: |
      The label of the dropdown
    type: string

  description:
    description: |
      The description of the dropdown
    type: string

  commit_message:
    type: string

  dry_run:
    description: |
      see https://github.com/ShaMan123/gha-form-dropdown-options for the rest
    type: choice
    options:
      - no-write
      - no-commit
      - no-push

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-declaring-outputs-for-composite-actions
outputs:
  tags:
    description: A stringified array of the resulting tags
    value: ${{ steps.main.outputs.tags }}

  latest:
    description: Latest tag of `package` in `registry`
    value: ${{ steps.main.outputs.latest }}

  # inherited from https://github.com/ShaMan123/gha-form-dropdown-options

  form:
    description: JSON stringified form
    value: ${{ steps.write.outputs.form }}

  modified:
    description: |
      see https://github.com/ShaMan123/gha-form-dropdown-options
    value: ${{ steps.write.outputs.modified }}

  pushed:
    description: |
      see https://github.com/ShaMan123/gha-form-dropdown-options
    value: ${{ steps.write.outputs.pushed }}

runs:
  using: composite
  steps:
    - name: Fetch tags from ${{ inputs.registry }}:${{ inputs.package }}
      id: main
      if: ${{ !inputs.tags }}
      run: |
        node ${{ github.action_path }}/dist/main.cjs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_ORDER: ${{ inputs.order }}
        INPUT_LIMIT_TO: ${{ inputs.limit_to }}
        INPUT_SEMVER: ${{ inputs.semver }}
    - name: Set dropdown options
      id: write
      uses: ynput/gha-form-dropdown-options@main
      with:
        github_token: ${{ inputs.github_token }}
        github_user: ${{ inputs.github_user }}
        github_email: ${{ inputs.github_email }}
        template: ${{ inputs.template }}
        form: ${{ inputs.form }}
        dropdown: ${{ inputs.dropdown }}
        options: ${{ inputs.tags || steps.main.outputs.tags }}
        commit_message: ${{ inputs.commit_message }}
        dry_run: ${{ inputs.dry_run }}
