name: Populate Yaml Dropdown Version
description: Populates the package version dropdown of a yaml form
author: ShaMan123
branding:
  icon: hash
  color: black
inputs:
  github_token:
    description: Github token
    default: ${{ github.token }}
  form:
    description: 'The location of the yaml form file'
    default: '.github/ISSUE_TEMPLATE/bug_report.yml'
    type: string
  dropdown:
    description: 'The id of the dropdown in the yaml form to populate tags into'
    default: 'version'
    type: string
  package:
    description: 'The name of the published package'
    default: ${{ github.event.repository.name }}
    type: string
  registry:
    description: 'The name of the registry the package is published at'
    default: 'npm'
    type: string
    options:
      - npm
      - github
  order:
    description: 'Display order of populated tags (`asc | desc`)'
    default: 'desc'
    type: choice
    options:
      - desc
      - asc
  limit_to:
    description: 'limit populated tags'
    type: number
  # tags:
  #   description: 'Provide an array of tags instead of fetching from the `registry`, overrides `package`, `registry`, `order`, `limit_to`'
  #   type: sequence
  commit_message:
    default: 'chore(): update bug report version'
    type: string
outputs:
  tags:
    description: an array of the resulting tags
runs:
  using: composite
  steps:
    # - run: git pull
    #   shell: bash
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.repository.default_branch }}
    - name: Update ${{ inputs.form }}
      run: node dist/main.cjs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_FORM: ${{ inputs.form }}
        INPUT_DROPDOWN: ${{ inputs.dropdown }}
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_ORDER: ${{ inputs.order }}
        INPUT_LIMIT_TO: ${{ inputs.limit_to }}
        # INPUT_TAGS: ${{ inputs.tags }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
    - name: Commit to ${{ github.event.repository.default_branch }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ${{ inputs.form }}
        git commit -m "${{ inputs.commit_message }}"
        git push
      shell: bash
