name: ðŸ› Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Before you be
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: fabric
    attributes:
      label: fabric npm version
      description: >-
        fabric npm
      options:
        - 5.2.4
    validations:
      required: true
  - type: dropdown
    id: fabric_tags
    attributes:
      label: fabric tags
      description: >-
        fabric tags
      options:
        - 5.2.4
    validations:
      required: true
  - type: dropdown
    id: lodash
    attributes:
      label: lodash version
      description: lodash
      options:
        - 4.17.21
        - 4.17.20
        - 4.17.19
        - 4.17.18
        - 4.17.17
        - 4.17.16
        - 4.17.15
        - 4.17.14
        - 4.17.13
        - 4.17.12
        - 4.17.11
        - 4.17.10
        - 4.17.9
        - 4.17.5
        - 4.17.4
        - 4.17.3
        - 4.17.2
        - 4.17.1
        - 4.17.0
        - 4.16.6
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Releases
      description: Releases of this repo
      options:
        - v0.2.0
        - v0.1.21
    validations:
      required: true
  - type: dropdown
    id: math
    attributes:
      label: 'Using action owner: `react-native-math-view`'
      description: Releases of this repo
      options:
        - v0.2.0
        - v0.1.21
    validations:
      required: true
  - type: dropdown
    id: node_version
    attributes:
      label: Node Version (if applicable)
      options:
        -
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
