name: 🐛 Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Before you be
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: version
    attributes:
      label: version
      description: >-
        If you are working on a version below latest you should upgrade to
        latest before filing a bug report, your issue might have been resolved
        already.
      options:
        - v0.1.21
        - v0.1.19
        - v0.1.18
        - v0.1.17
        - v0.1.16
        - v0.1.15
        - v0.1.14
        - v0.1.13
        - v0.1.12
        - v0.1.11
        - v0.1.2
        - v0.1.1
        - v0.1.0
    validations:
      required: true
  - type: dropdown
    id: lodash
    attributes:
      label: lodash version
      description: lodash
      options:
        - v0.1.21
        - v0.1.19
        - v0.1.18
        - v0.1.17
        - v0.1.16
        - v0.1.15
        - v0.1.14
        - v0.1.13
        - v0.1.12
        - v0.1.11
        - v0.1.2
        - v0.1.1
        - v0.1.0
    validations:
      required: true
  - type: dropdown
    id: self
    attributes:
      label: Releases
      description: Releases of this repo
      options:
        - v0.1.21
    validations:
      required: true
  - type: input
    id: node_version
    attributes:
      label: Node Version (if applicable)
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
