name: 🐛 Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Before you begin
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: _version
    attributes:
      label: Select Release Version
      options:
        - v2.0.3
        - v2.0.2
        - v2.0.1
        - v2.0.0
        - v1.2.0-rc.2
        - v1.2.0-rc.1
        - v1.2.0-rc.0
        - v1.2.0
        - v1.1.0
        - v1.0.0
        - v0.4.3
        - v0.4.2
        - v0.4.1
        - v0.4.0
        - v0.3.2
        - v0.3.1
        - v0.3.0
        - v0.2.1-rc1
        - v0.2.1-rc
        - v0.2.0
        - v0.1.21
        - v0.1.19
        - v0.1.18
        - v0.1.17
        - v0.1.16
        - v0.1.15
        - v0.1.14
        - v0.1.13
        - v0.1.12
        - v0.1.11
        - v0.1.2
        - v0.1.1
        - v0.1.0
    validations:
      required: true
  - type: dropdown
    id: _node_version
    attributes:
      label: Select Node Version
      options:
        - 19.2.0
        - 19.1.0
        - 19.0.1
        - 19.0.0
        - 18.12.1
        - 18.12.0
        - 18.11.0
        - 18.10.0
        - 18.9.1
        - 18.9.0
        - 18.8.0
        - 18.7.0
        - 18.6.0
        - 18.5.0
        - 18.4.0
        - 18.3.0
        - 18.2.0
        - 18.1.0
        - 18.0.0
        - 17.9.1
        - 17.7.2
        - 17.7.1
        - 17.7.0
        - 17.6.0
        - 17.5.0
        - 17.4.0
        - 17.3.1
        - 17.3.0
        - 17.2.0
        - 17.1.0
        - 17.0.1
        - 17.0.0
        - 16.18.1
        - 16.18.0
        - 16.17.1
        - 16.17.0
        - 16.16.0
        - 16.15.1
        - 16.15.0
        - 16.14.2
        - 16.14.1
        - 16.14.0
        - 16.13.2
        - 16.13.1
        - 16.13.0
        - 16.12.0
        - 16.11.1
        - 16.11.0
        - 16.10.0
        - 16.9.1
        - 16.9.0
        - 16.8.0
        - 16.7.0
        - 16.6.2
        - 16.6.1
        - 16.6.0
        - 16.5.0
        - 16.4.1
        - 16.4.0
        - 16.3.0
        - 16.1.0
        - 16.0.0
        - 15.14.0
        - 15.12.0
        - 15.10.0
        - 15.8.0
        - 15.7.0
        - 15.4.0
        - 15.3.0
        - 15.2.1
        - 15.2.0
        - 15.1.0
        - 15.0.1
        - 15.0.0
        - 14.21.0
        - 14.20.1
        - 14.20.0
        - 14.19.3
        - 14.19.2
        - 14.19.1
        - 14.19.0
        - 14.18.3
        - 14.18.2
        - 14.18.1
        - 14.18.0
        - 14.17.6
        - 14.17.5
        - 14.17.4
        - 14.17.3
        - 14.17.2
        - 14.17.1
        - 14.16.1
        - 14.16.0
        - 14.15.2
        - 14.15.1
        - 14.15.0
        - 14.14.0
        - 14.13.1
        - 14.13.0
        - 14.12.0
        - 14.11.0
        - 14.10.1
        - 14.10.0
        - 14.9.0
        - 14.8.0
        - 14.7.0
        - 14.6.0
        - 14.5.0
        - 14.4.0
        - 14.3.0
        - 14.2.0
        - 14.1.0
        - 14.0.0
        - 13.14.0
        - 13.13.0
        - 13.12.0
        - 13.11.0
        - 13.10.1
        - 13.10.0
        - 13.9.0
        - 13.8.0
        - 13.7.0
        - 13.6.0
        - 13.5.0
        - 13.4.0
        - 13.3.0
        - 13.2.0
        - 13.1.0
        - 13.0.1
        - 13.0.0
        - 12.22.12
        - 12.22.11
        - 12.22.10
        - 12.22.9
        - 12.22.8
        - 12.22.7
        - 12.22.6
        - 12.22.5
        - 12.22.4
        - 12.22.3
        - 12.22.2
        - 12.22.1
        - 12.21.0
        - 12.20.1
        - 12.20.0
        - 12.19.1
        - 12.19.0
        - 12.18.4
        - 12.18.3
        - 12.18.2
        - 12.18.1
        - 12.18.0
        - 12.17.0
        - 12.16.3
        - 12.16.2
        - 12.16.1
        - 12.16.0
        - 12.15.0
        - 12.14.1
        - 12.14.0
        - 12.13.1
        - 12.13.0
        - 12.12.0
        - 12.11.1
        - 12.11.0
        - 12.10.0
        - 12.9.1
        - 12.9.0
        - 12.8.1
        - 12.8.0
        - 12.7.0
        - 12.6.0
        - 12.5.0
        - 12.4.0
        - 12.3.1
        - 12.3.0
        - 12.2.0
        - 12.1.0
        - 12.0.0
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
