name: 🐛 Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Before you begin
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: $version
    attributes:
      label: Select Release Version
      options:
        - v1.2.0-rc.1
        - v1.2.0-rc.0
        - v1.2.0
        - v1.1.0
        - v1.0.0
        - v0.4.3
        - v0.4.2
        - v0.4.1
        - v0.4.0
        - v0.3.2
        - v0.3.1
        - v0.3.0
        - v0.2.1-rc1
        - v0.2.1-rc
        - v0.2.0
        - v0.1.21
        - v0.1.19
        - v0.1.18
        - v0.1.17
        - v0.1.16
        - v0.1.15
        - v0.1.14
        - v0.1.13
        - v0.1.12
        - v0.1.11
        - v0.1.2
        - v0.1.1
        - v0.1.0
    validations:
      required: true
  - type: dropdown
    id: $node_version
    attributes:
      label: Select Node Version
      options: 
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
