---
name: ðŸ¼ Demo Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Before you begin
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: _fabric
    attributes:
      label: npm version
      description: fabric npm
      options:
        - 6.6.4
        - 6.6.2
        - 6.6.1
        - 6.6.0
        - 6.5.4
        - 6.5.3
        - 6.5.2
        - 6.5.1
        - 6.5.0
        - 6.4.3
        - 6.4.2
        - 6.4.1
        - 6.4.0
        - 6.3.0
        - 6.2.0
        - 6.1.0
        - 6.0.2
        - 6.0.1
        - 6.0.0
        - 6.0.0-rc4
        - 6.0.0-rc3
        - 6.0.0-rc2
        - 6.0.0-rc1
        - 6.0.0-beta9
        - 6.0.0-beta8
        - 6.0.0-beta7
        - 6.0.0-beta6
        - 6.0.0-beta5
        - 6.0.0-beta4
        - 6.0.0-beta3
        - 6.0.0-beta20
        - 6.0.0-beta19
        - 6.0.0-beta18
        - 6.0.0-beta17
        - 6.0.0-beta16
        - 6.0.0-beta15
        - 6.0.0-beta14
        - 6.0.0-beta13
        - 6.0.0-beta12
        - 6.0.0-beta11
        - 6.0.0-beta10
        - 6.0.0-beta1
        - 5.5.2
        - 5.5.2-browser
        - 5.5.1
        - 5.5.1-browser
        - 5.5.0
        - 5.5.0-browser
        - 5.4.2
        - 5.4.2-browser
        - 5.4.1
        - 5.4.1-browser
        - 5.4.0
        - 5.4.0-browser
        - 5.3.0
        - 5.3.0-browser
        - 5.2.4
        - 5.2.4-browser
        - 5.2.2
        - 5.2.2-browser
        - 5.2.1
        - 5.2.1-browser
        - 5.1.0
        - 5.1.0-browser
        - 5.0.0
        - 5.0.0-browser
        - 4.6.0
        - 4.6.0-browser
        - 4.5.1
        - 4.5.1-browser
        - 4.5.0
        - 4.5.0-browser
        - 4.4.0
        - 4.4.0-browser
        - 4.3.1
        - 4.3.1-browser
        - 4.3.0
        - 4.3.0-browser
        - 4.2.0
        - 4.2.0-browser
        - 4.1.0
        - 4.1.0-browser
        - 4.0.0
        - 4.0.0-rc.1-browser
        - 4.0.0-rc.1
        - 4.0.0-browser
        - 4.0.0-beta1
        - 4.0.0-beta.9-browser
        - 4.0.0-beta.8-browser
        - 4.0.0-beta.7-browser
        - 4.0.0-beta.6-browser
        - 4.0.0-beta.5-browser
        - 4.0.0-beta.4-browser
        - 4.0.0-beta.12-browser
        - 4.0.0-beta.11-browser
        - 4.0.0-beta.10-browser
        - 4.0.0-beta.12
        - 4.0.0-beta.11
        - 4.0.0-beta.10
        - 4.0.0-beta.9
        - 4.0.0-beta.8
        - 4.0.0-beta.7
        - 4.0.0-beta.6
        - 4.0.0-beta.5
        - 4.0.0-beta.4
        - 4.0.0-beta.3
        - 4.0.0-beta.2
        - 3.6.6
        - 3.6.6-browser
        - 3.6.5
        - 3.6.5-browser
        - 3.6.4
        - 3.6.4-browser
        - 3.6.3
        - 3.6.3-browser
        - 3.6.2
        - 3.6.2-browser
        - 3.6.1
        - 3.6.1-browser
        - 3.6.0
        - 3.6.0-browser
        - 3.5.1
        - 3.5.1-browser
        - 3.5.0
        - 3.5.0-browser
        - 3.4.0
        - 3.4.0-browser
        - 3.3.2
        - 3.3.2-browser
        - 3.3.1
        - 3.3.1-browser
        - 3.3.0
        - 3.3.0-browser
        - 3.2.0
        - 3.1.0
        - 3.0.0
        - 2.7.0
        - 2.6.0
        - 2.5.0
        - 2.4.6
        - 2.4.5
        - 2.4.4
        - 2.4.3
        - 2.4.2
        - 2.4.2-b
        - 2.4.1
        - 2.4.0
        - 2.3.6
        - 2.3.5
        - 2.3.4
        - 2.3.3
        - 2.3.2
        - 2.3.1
        - 2.3.0
        - 2.2.4
        - 2.2.3
        - 2.2.2
        - 2.2.1
        - 2.2.0
        - 2.1.0
        - 2.0.3
        - 2.0.2
        - 2.0.1
        - 2.0.0
        - 2.0.0-rc.4
        - 2.0.0-rc.3
        - 2.0.0-rc.2
        - 2.0.0-rc.1
        - 2.0.0-beta0
        - 2.0.0-beta.7
        - 2.0.0-beta.6
        - 2.0.0-beta.5
        - 2.0.0-beta.4
        - 2.0.0-beta.3
        - 2.0.0-beta.2
        - 2.0.0-beta.1
        - 1.7.22
        - 1.7.21
        - 1.7.20
        - 1.7.19
        - 1.7.18
        - 1.7.17
        - 1.7.16
        - 1.7.15
        - 1.7.14
        - 1.7.13
        - 1.7.12
        - 1.7.11
        - 1.7.10
        - 1.7.9
        - 1.7.8
        - 1.7.7
        - 1.7.6
        - 1.7.4
        - 1.7.3
        - 1.7.2
        - 1.7.1
        - 1.7.0
        - 1.6.7
        - 1.6.6
        - 1.6.5
        - 1.6.4
        - 1.6.3
        - 1.6.2
        - 1.6.1
        - 1.6.0
        - 1.6.0-rc.1
        - 1.5.0
        - 1.4.13
        - 1.4.12
        - 1.4.11
        - 1.4.9
        - 1.4.7
        - 1.4.6
        - 1.4.3
        - 1.4.2
        - 1.4.1
        - 1.4.0
        - 1.3.12
        - 1.3.9
        - 1.3.8
        - 1.3.7
        - 1.3.6
        - 1.3.5
        - 1.3.4
        - 1.3.3
        - 1.3.2
        - 1.3.1
        - 1.2.11
        - 1.2.10
        - 1.2.9
        - 1.2.6
        - 1.2.5
        - 1.2.4
        - 1.2.3
        - 1.2.2
        - 1.2.1
        - 1.2.0
        - 1.1.21
        - 1.1.20
        - 1.1.19
        - 1.1.18
        - 1.1.16
        - 1.1.14
        - 1.1.13
        - 1.1.11
        - 1.1.9
        - 1.1.6
        - 1.1.4
        - 1.1.3
        - 1.0.9
        - 1.0.8
        - 1.0.7
        - 1.0.6
        - 1.0.1
        - 1.0.0
        - 0.9.21
        - 0.9.19
        - 0.9.17
        - 0.9.14
        - 0.9.10
        - 0.9.9
        - 0.9.8
        - 0.9.7
        - 0.9.5
        - 0.9.3
        - 0.9.2
        - 0.9.1
        - 0.9.0
        - 0.8.52
        - 0.8.51
        - 0.8.50
        - 0.8.47
        - 0.8.46
        - 0.8.44
        - 0.8.42
        - 0.8.35
        - 0.8.34
        - 0.8.26
        - 0.8.20
        - 0.8.19
        - 0.8.13
        - 0.8.12
        - 0.8.11
        - 0.8.10
        - 0.8.7
        - 0.8.4
        - 0.8.0
        - 0.7.24
        - 0.7.23
        - 0.7.22
        - 0.7.18
        - 0.7.17
        - 0.7.16
        - 0.7.15
        - 0.7.14
        - 0.7.13
        - 0.7.11
        - 0.7.9
        - 0.7.4
        - 0.7.3
        - 0.7.1
        - 0.6.12
        - 0.6.8
        - 0.6.7
        - 0.6.6
        - 0.6.4
        - 0.5.13
        - 0.5.10
        - 0.5.7
        - 0.5.6
        - 0.5.5
        - 0.5.3
        - 0.5.2
    validations:
      required: true
  - type: dropdown
    id: _fabric_tags
    attributes:
      label: Github Releases
      description: fabric tags
      options:
        - v664
        - v663
        - v552
        - v662
        - v661
        - v660
        - v654
        - v551
        - v550
        - v653
        - v652
        - v651
        - v542b
        - v650
        - v541
        - v643
        - v642
        - v641
        - v640
        - v630
        - v620
        - v610
        - v540
        - v6.0.2
        - v6.0.1
        - v6.0.0-rc5
        - v6.0.0-rc4
        - v6.0.0-rc3
        - v6.0.0-rc2
        - v6.0.0-rc1
        - v6.0.0-beta20
        - v6.0.0-beta19
        - v6.0.0-beta18
        - v6.0.0-beta17
        - v6.0.0-beta16
        - v6.0.0-beta15
        - v6.0.0-beta14
        - v6.0.0-beta13
        - v6.0.0-beta12
        - v6.0.0-beta11
        - v6.0.0-beta10
        - v6.0.0-beta9
        - v6.0.0-beta8
        - v6.0.0-beta7
        - v6.0.0-beta6
        - v6.0.0-beta5
        - v6.0.0-beta4
        - v6.0.0-beta3
        - v6.0.0-beta2
        - v6.0.0-beta1
        - v5.3.1
        - v5.2.4
        - v5.2.3
        - v521
        - v520
        - v510
        - v500
        - v460
        - v451
        - v4.5.0
        - v4.4.0
        - v4.3.1
        - v4.3.0
        - v4.2.0
        - v4.1.0
        - v3.6.6
        - v3.6.5
        - v3.6.4
        - v4.0.0
        - v4.0.0-rc.1
        - v4.0.0-beta.12
        - v4.0.0-beta.11
        - v4.0.0-beta.10
        - v4.0.0-beta.9
        - v4.0.0-beta.8
        - v363
        - v3.6.3
        - v4.0.0-beta.7
        - v4.0.0-beta.6
        - v3.6.2
        - 4.0.0-beta.5
        - v4.0.0-beta.4
        - v4.0.0-beta.3
        - v4.0.0-beta.2
        - v4.0.0-beta.1
        - v3.6.1
        - v3.6.0
        - v3.5.0
        - v3.4.0
        - 3.3.2
        - v3.2.0
        - v3.1.0
        - v3.0.0
        - v2.7.0
        - v2.6.0
        - v2.5.0
        - v2.4.6
        - v2.4.5
        - v2.4.4
        - v2.4.3
        - v2.4.2
        - 2.4.2-b
        - v2.4.1
        - v2.4.0
        - v2.3.6
        - v2.3.5
        - v2.3.4
        - v2.3.3
        - v2.3.2
        - v2.3.1
        - v2.3.0
        - v2.2.4
        - v2.2.3
        - v2.2.2
        - v2.2.1
        - v2.2.0
        - v2.1.0
        - v2.0.3
        - v2.0.2
        - v2.0.1
        - v2.0.0
        - 1.7.22
        - v2.0.0-rc.4
        - 1.7.21
        - v2.0.0-rc.3
        - v2.0.0-rc.2
        - v2.0.0-rc.1
        - v1.7.20
        - v2.0.0-beta.7
        - v1.7.19
        - v1.7.18
        - v2.0.0-beta.6
        - v2.0.0-beta.4
        - v1.7.17
        - v1.7.16
        - v2.0.0-beta.3
        - v1.7.15
        - v1.7.14
        - v1.7.13
        - v1.7.12
        - v1.7.11
        - v1.7.10
        - v2.0.0-beta.1
        - v1.7.9
        - v1.7.8
        - v1.7.7
        - v1.7.6
        - v1.7.5
        - 1.7.4
        - v1.7.3
        - v1.7.2
        - v1.7.1
        - 1.7.0
        - v1.6.7
        - v1.6.6
        - v1.6.5
        - 1.6.4
        - 1.6.3
        - 1.6.2
        - v1.6.1
        - v1.6.0
        - v1.5.0
        - v1.4.13
        - v1.4.12
        - v1.4.11
        - v1.4.10
        - v1.4.9
        - v1.4.8
        - v1.4.0
    validations:
      required: true
  - type: dropdown
    id: _lodash
    attributes:
      label: limit to 20
      description: lodash
      options:
        - 4.17.21
        - 4.17.20
        - 4.17.19
        - 4.17.18
        - 4.17.17
        - 4.17.16
        - 4.17.15
        - 4.17.14
        - 4.17.13
        - 4.17.12
        - 4.17.11
        - 4.17.10
        - 4.17.9
        - 4.17.5
        - 4.17.4
        - 4.17.3
        - 4.17.2
        - 4.17.1
        - 4.17.0
        - 4.16.6
    validations:
      required: true
  - type: dropdown
    id: _version
    attributes:
      label: Github releases of triggering repo + semver option
      description: Releases of this repo
      options:
        - v2.0.3
        - v2.0.2
        - v2.0.1
        - v2.0.0
        - v1.2.0
        - v1.1.0
        - v1.0.0
        - v0.4.3
        - v0.4.2
        - v0.4.1
        - v0.4.0
        - v0.3.2
        - v0.3.1
        - v0.3.0
        - v0.2.0
        - v0.1.21
    validations:
      required: true
  - type: dropdown
    id: _math
    attributes:
      label: Using owner of triggering repo
      description: Releases of `react-native-math-view`
      options:
        - 3.4.9
    validations:
      required: true
  - type: dropdown
    id: _node_version
    attributes:
      label: asc, limit to 15
      description: node npm
      options:
        - 0.0.0
        - 0.1.14
        - 0.1.15
        - 0.1.16
        - 0.1.17
        - 0.1.18
        - 0.1.19
        - 0.1.20
        - 0.1.21
        - 0.1.22
        - 0.1.23
        - 0.1.24
        - 0.1.25
        - 0.1.26
        - 0.1.27
    validations:
      required: false
  - type: dropdown
    id: _copy
    attributes:
      label: Using `outputs.tags` from a dry run
      description: Axios npm
      options:
        - 1.0.0-alpha.1
        - 0.27.2
        - 0.27.1
        - 0.27.0
        - 0.26.1
        - 0.26.0
        - 0.25.0
        - 0.24.0
        - 0.23.0
        - 0.22.0
    validations:
      required: false
  - type: dropdown
    id: _generated
    attributes:
      label: Generated Tags
      description: >-
        Created using `actions/github-script@v6` and mixed with outputs of
        previous steps
      options:
        - 1.2.3
        - 4.5.6
        - 7.8.9
        - node@18.10.0
        - fabric@5.2.4
        - lodash@4.17.21
        - lodash@4.17.20
        - lodash@4.17.19
        - lodash@4.17.18
        - lodash@4.17.17
        - pixijs@v6.5.5
        - pixijs@v7.0.0-alpha.3
        - pixijs@v6.5.4
        - pixijs@v7.0.0-alpha.2
        - pixijs@v7.0.0-alpha
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
