---
name: ðŸ¼ Demo Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Before you begin
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: _erase2d
    attributes:
      label: npm version
      description: '@erase2/fabric npm'
      options:
        - 1.1.7
        - 1.1.6
        - 1.1.5
        - 1.1.4
        - 1.1.3
        - 1.1.2
        - 1.1.1
        - 1.1.0
        - 1.1.0-1
        - 1.0.0
    validations:
      required: true
  - type: dropdown
    id: _fabric_tags
    attributes:
      label: Github Releases
      description: fabric tags
      options:
        - v664
        - v663
        - v552
        - v662
        - v661
        - v660
        - v654
        - v551
        - v550
        - v653
        - v652
        - v651
        - v542b
        - v650
        - v541
        - v643
        - v642
        - v641
        - v640
        - v630
        - v620
        - v610
        - v540
        - v6.0.2
        - v6.0.1
        - v6.0.0-rc5
        - v6.0.0-rc4
        - v6.0.0-rc3
        - v6.0.0-rc2
        - v6.0.0-rc1
        - v6.0.0-beta20
        - v6.0.0-beta19
        - v6.0.0-beta18
        - v6.0.0-beta17
        - v6.0.0-beta16
        - v6.0.0-beta15
        - v6.0.0-beta14
        - v6.0.0-beta13
        - v6.0.0-beta12
        - v6.0.0-beta11
        - v6.0.0-beta10
        - v6.0.0-beta9
        - v6.0.0-beta8
        - v6.0.0-beta7
        - v6.0.0-beta6
        - v6.0.0-beta5
        - v6.0.0-beta4
        - v6.0.0-beta3
        - v6.0.0-beta2
        - v6.0.0-beta1
        - v5.3.1
        - v5.2.4
        - v5.2.3
        - v521
        - v520
        - v510
        - v500
        - v460
        - v451
        - v4.5.0
        - v4.4.0
        - v4.3.1
        - v4.3.0
        - v4.2.0
        - v4.1.0
        - v3.6.6
        - v3.6.5
        - v3.6.4
        - v4.0.0
        - v4.0.0-rc.1
        - v4.0.0-beta.12
        - v4.0.0-beta.11
        - v4.0.0-beta.10
        - v4.0.0-beta.9
        - v4.0.0-beta.8
        - v363
        - v3.6.3
        - v4.0.0-beta.7
        - v4.0.0-beta.6
        - v3.6.2
        - 4.0.0-beta.5
        - v4.0.0-beta.4
        - v4.0.0-beta.3
        - v4.0.0-beta.2
        - v4.0.0-beta.1
        - v3.6.1
        - v3.6.0
        - v3.5.0
        - v3.4.0
        - 3.3.2
        - v3.2.0
        - v3.1.0
        - v3.0.0
        - v2.7.0
        - v2.6.0
        - v2.5.0
        - v2.4.6
        - v2.4.5
        - v2.4.4
        - v2.4.3
        - v2.4.2
        - 2.4.2-b
        - v2.4.1
        - v2.4.0
        - v2.3.6
        - v2.3.5
        - v2.3.4
        - v2.3.3
        - v2.3.2
        - v2.3.1
        - v2.3.0
        - v2.2.4
        - v2.2.3
        - v2.2.2
        - v2.2.1
        - v2.2.0
        - v2.1.0
        - v2.0.3
        - v2.0.2
        - v2.0.1
        - v2.0.0
        - 1.7.22
        - v2.0.0-rc.4
        - 1.7.21
        - v2.0.0-rc.3
        - v2.0.0-rc.2
        - v2.0.0-rc.1
        - v1.7.20
        - v2.0.0-beta.7
        - v1.7.19
        - v1.7.18
        - v2.0.0-beta.6
        - v2.0.0-beta.4
        - v1.7.17
        - v1.7.16
        - v2.0.0-beta.3
        - v1.7.15
        - v1.7.14
        - v1.7.13
        - v1.7.12
        - v1.7.11
        - v1.7.10
        - v2.0.0-beta.1
        - v1.7.9
        - v1.7.8
        - v1.7.7
        - v1.7.6
        - v1.7.5
        - 1.7.4
        - v1.7.3
        - v1.7.2
        - v1.7.1
        - 1.7.0
        - v1.6.7
        - v1.6.6
        - v1.6.5
        - 1.6.4
        - 1.6.3
        - 1.6.2
        - v1.6.1
        - v1.6.0
        - v1.5.0
        - v1.4.13
        - v1.4.12
        - v1.4.11
        - v1.4.10
        - v1.4.9
        - v1.4.8
        - v1.4.0
    validations:
      required: true
  - type: dropdown
    id: _lodash
    attributes:
      label: limit to 20
      description: lodash
      options:
        - 4.17.21
        - 4.17.20
        - 4.17.19
        - 4.17.18
        - 4.17.17
        - 4.17.16
        - 4.17.15
        - 4.17.14
        - 4.17.13
        - 4.17.12
        - 4.17.11
        - 4.17.10
        - 4.17.9
        - 4.17.5
        - 4.17.4
        - 4.17.3
        - 4.17.2
        - 4.17.1
        - 4.17.0
        - 4.16.6
    validations:
      required: true
  - type: dropdown
    id: _version
    attributes:
      label: Github releases of triggering repo + semver option
      description: Releases of this repo
      options:
        - v2.0.5
        - v2.0.3
        - v2.0.2
        - v2.0.1
        - v2.0.0
        - v1.2.0
        - v1.1.0
        - v1.0.0
        - v0.4.3
        - v0.4.2
        - v0.4.1
        - v0.4.0
        - v0.3.2
        - v0.3.1
        - v0.3.0
        - v0.2.0
        - v0.1.21
    validations:
      required: true
  - type: dropdown
    id: _math
    attributes:
      label: Using owner of triggering repo
      description: Releases of `react-native-math-view`
      options:
        - 3.4.9
    validations:
      required: true
  - type: dropdown
    id: _node_version
    attributes:
      label: asc, limit to 15
      description: node npm
      options:
        - 0.0.0
        - 0.1.14
        - 0.1.15
        - 0.1.16
        - 0.1.17
        - 0.1.18
        - 0.1.19
        - 0.1.20
        - 0.1.21
        - 0.1.22
        - 0.1.23
        - 0.1.24
        - 0.1.25
        - 0.1.26
        - 0.1.27
    validations:
      required: false
  - type: dropdown
    id: _copy
    attributes:
      label: Using `outputs.tags` from a dry run
      description: Axios npm
      options:
        - 1.9.0
        - 1.8.4
        - 1.8.3
        - 1.8.2
        - 1.8.1
        - 1.8.0
        - 1.7.9
        - 1.7.8
        - 1.7.7
        - 1.7.6
    validations:
      required: false
  - type: dropdown
    id: _generated
    attributes:
      label: Generated Tags
      description: >-
        Created using `actions/github-script@v6` and mixed with outputs of
        previous steps
      options:
        - 1.2.3
        - 4.5.6
        - 7.8.9
        - node@23.11.0
        - erase2d/fabric@1.1.7
        - lodash@4.17.21
        - lodash@4.17.20
        - lodash@4.17.19
        - lodash@4.17.18
        - lodash@4.17.17
        - pixijs@v8.9.2
        - pixijs@v8.9.1
        - pixijs@v8.9.0
        - pixijs@v7.4.3
        - pixijs@v8.8.1
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
