name: Publish

on:
  push:
    branches:
      - main
  release:
    branches:
      - main
    types: [published]

jobs:
  update-bug-report:
    runs-on: ubuntu-latest
    name: Update bug report version to ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v2
      - name: Update bug report fabric
        uses: ./
        with:
          package: fabric
      - name: Update bug report lodash
        uses: ./
        with:
          package: lodash
          dropdown-id: lodash
