name: Publish

on:
  push:
    branches:
      - '*'
  release:
    branches:
      - main
    types: [published]

jobs:
  update-bug-report:
    runs-on: ubuntu-latest
    name: Update bug report
    steps:
      - uses: actions/checkout@v3
      - name: Update bug report fabric
        uses: ./
        with:
          package: fabric
      - name: Update bug report lodash
        uses: ./
        with:
          package: lodash
          dropdown: lodash
          limit_to: 20
      - name: Update bug report self
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dropdown: self
          registry: github
